version: "3.9"

services:
  shortb-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: ShortDB
      TZ: America/Sao_Paulo

  shortb-adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - shortb-db

  shortb-api:
    image: beyondtest/shortb-api:hotfix
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_URL: postgres://dba:dba@shortb-db:5432/ShortDB?sslmode=disable
      JWT_SECRET: vaiplaneta
    depends_on:
      - shortb-db

  shortb-web:
    image: beyondtest/shortb-web:latest
    ports:
      - "80:80"
    depends_on:
      - shortb-api
