name: Playwright API Tests (Podman)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Instala Podman + Podman Compose
      - name: Install Podman and podman-compose
        run: |
          sudo apt-get update
          sudo apt-get -y install podman podman-compose

      # Sobe containers do ambiente definido em podman-compose.yml
      - name: Start environment with Podman
        run: podman-compose -f podman-compose.yml up -d

      # Aguarda API responder antes de rodar testes
      - name: Wait for API
        run: |
          echo "Aguardando API subir..."
          for i in {1..30}; do
            if curl -s http://localhost:3333/health > /dev/null; then
              echo "API disponível!"
              exit 0
            fi
            sleep 2
          done
          echo "API não respondeu a tempo"
          exit 1

      - name: Run Playwright tests
        run: npm run pw-run -- --reporter=list --reporter=html

      - name: Ensure report dir exists
        if: always()
        run: mkdir -p playwright-report

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # Finaliza containers para liberar runner
      - name: Shutdown environment
        if: always()
        run: podman-compose -f podman-compose.yml down
